spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DATABASE_SCHEMA:wallet_schema}
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${DATABASE_SCHEMA:wallet_schema}
      connection-timeout: ${DATABASE_CONNECTION_TIMEOUT:10000}

  jpa:
    properties:
      hibernate:
        show_sql: false
        hbm2ddl:
          auto: none
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true